#!/bin/bash
# Full deployment: do2 (VPS1) + fominet (VPS2/OpenWRT)
# Run from local machine (PC1)
# Usage: ./deploy-all.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

DO2_HOST="do2"              # SSH config alias
DO2_IP="152.42.238.137"
FOMINET_HOST="fominet"      # SSH config alias (192.168.20.1)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[DEPLOY]${NC} $1"; }
step() { echo -e "${BLUE}[STEP]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        SD-WAN Lab 3 Method-2 Deployment                     ║"
echo "║  do2 (VPS1/Hub) + fominet (VPS2/OpenWRT Exit Node)          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ─── Step 1: Check SSH ───
step "1/7 - Checking SSH connectivity..."
ssh -o ConnectTimeout=5 -o BatchMode=yes $DO2_HOST "echo 'do2 OK'" || error "Cannot SSH to do2"
ssh -o ConnectTimeout=10 -o BatchMode=yes $FOMINET_HOST "echo 'fominet OK'" || error "Cannot SSH to fominet"
log "SSH connectivity OK"

# ─── Step 2: Upload to do2 ───
step "2/7 - Uploading scripts to do2..."
ssh $DO2_HOST "mkdir -p /etc/sdwan"
scp "$SCRIPT_DIR/deploy-do2.sh" $DO2_HOST:/tmp/
scp "$SCRIPT_DIR/routing-setup.sh" $DO2_HOST:/tmp/

# Upload China IPs
if [ -f "$PROJECT_DIR/chinaip.json" ]; then
    log "Uploading China IPs list..."
    scp "$PROJECT_DIR/chinaip.json" $DO2_HOST:/etc/sdwan/chinaip.txt
fi

# ─── Step 3: Upload to fominet ───
step "3/7 - Uploading scripts to fominet..."
scp "$SCRIPT_DIR/deploy-fominet.sh" $FOMINET_HOST:/tmp/

# ─── Step 4: Deploy fominet first (exit node) ───
step "4/7 - Deploying fominet (VPS2/Exit Node)..."
ssh $FOMINET_HOST "chmod +x /tmp/deploy-fominet.sh && /tmp/deploy-fominet.sh --force" || error "fominet deployment failed"
FOMINET_WG1_PUBKEY=$(ssh $FOMINET_HOST "cat /etc/wireguard/wg1_publickey")
log "fominet deployed. wg1 pubkey: $FOMINET_WG1_PUBKEY"

# ─── Step 5: Deploy do2 ───
step "5/7 - Deploying do2 (VPS1/Hub)..."
ssh $DO2_HOST "chmod +x /tmp/deploy-do2.sh && /tmp/deploy-do2.sh --force '$FOMINET_WG1_PUBKEY'" || error "do2 deployment failed"
DO2_WG1_PUBKEY=$(ssh $DO2_HOST "cat /etc/wireguard/wg1_publickey")
log "do2 deployed. wg1 pubkey: $DO2_WG1_PUBKEY"

# ─── Step 6: Link do2 ↔ fominet ───
step "6/7 - Linking do2 ↔ fominet..."
# Update do2 with fominet's pubkey
ssh $DO2_HOST "wg set wg1 peer $FOMINET_WG1_PUBKEY allowed-ips 10.20.0.2/32,0.0.0.0/0 endpoint thatnghiep.ddns.net:51821 persistent-keepalive 25"
ssh $DO2_HOST "echo '$FOMINET_WG1_PUBKEY' > /etc/wireguard/fominet_wg1_pubkey"

# Update fominet with do2's pubkey (via UCI)
ssh $FOMINET_HOST "uci set network.@wireguard_wg1[0].public_key='$DO2_WG1_PUBKEY' && uci commit network && /etc/init.d/network restart"

# Verify tunnel
log "Verifying do2 ↔ fominet tunnel..."
sleep 3
ssh $DO2_HOST "ping -c 2 -W 3 10.20.0.2" && log "do2 → fominet: OK" || warn "do2 → fominet: FAILED"
ssh $FOMINET_HOST "ping -c 2 -W 3 10.20.0.1" && log "fominet → do2: OK" || warn "fominet → do2: FAILED"

# ─── Step 7: Generate PC1 config ───
step "7/7 - Generating PC1 config..."
DO2_WG0_PUBKEY=$(ssh $DO2_HOST "cat /etc/wireguard/wg0_publickey")
PC1_CONFIG="$PROJECT_DIR/configs/method-2/pc1/wg0.conf"

PC1_PRIVKEY=$(wg genkey)
PC1_PUBKEY=$(echo "$PC1_PRIVKEY" | wg pubkey)

cat > "$PC1_CONFIG" << EOF
# PC1 - WireGuard Client
# Generated by deploy-all.sh on $(date)
# do2 (VPS1): $DO2_IP
# Split: China IPs → fominet, Other IPs → do2

[Interface]
Address = 10.10.0.2/24
PrivateKey = $PC1_PRIVKEY
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = $DO2_WG0_PUBKEY
Endpoint = $DO2_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF

# Register PC1 with do2
ssh $DO2_HOST "wg set wg0 peer $PC1_PUBKEY allowed-ips 10.10.0.2/32"
log "PC1 config generated and registered"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    DEPLOYMENT COMPLETE                       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Architecture:"
echo "  PC1 (10.10.0.2) ──wg0──► do2 (10.10.0.1 / 10.20.0.1)"
echo "                              │"
echo "                    ┌─────────┴─────────┐"
echo "                    │                   │"
echo "               Other IPs           China IPs"
echo "                    │                   │"
echo "               do2 eth0            wg1 → fominet"
echo "            ($DO2_IP)         (thatnghiep.ddns.net)"
echo ""
echo "PC1 Config: $PC1_CONFIG"
echo ""
echo "To connect PC1:"
echo "  sudo cp $PC1_CONFIG /etc/wireguard/wg0.conf"
echo "  sudo wg-quick up wg0"
echo ""
echo "Test:"
echo "  curl ifconfig.me                 # Should show do2 IP (other)"
echo "  curl --connect-to ::223.5.5.5: ifconfig.me  # China IP test"
echo "  traceroute 8.8.8.8              # Through do2"
echo "  traceroute 223.5.5.5            # Through fominet"
