#!/bin/bash
# Full deployment script - run from local machine
# Usage: ./deploy-all.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

VPS1_IP="103.109.187.182"
VPS2_IP="103.109.187.179"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[DEPLOY]${NC} $1"; }
step() { echo -e "${BLUE}[STEP]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           SD-WAN Method-2 Full Deployment                   ║"
echo "║  PC1 → VPS1 → VPS2 (exit) / China IPs exit at VPS1          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check SSH connectivity
step "1/6 - Checking SSH connectivity..."
ssh -o ConnectTimeout=5 -o BatchMode=yes root@$VPS1_IP "echo 'VPS1 OK'" || error "Cannot SSH to VPS1"
ssh -o ConnectTimeout=5 -o BatchMode=yes root@$VPS2_IP "echo 'VPS2 OK'" || error "Cannot SSH to VPS2"
log "SSH connectivity OK"

# Upload scripts to VPS1
step "2/6 - Uploading scripts to VPS1..."
ssh root@$VPS1_IP "mkdir -p /etc/sdwan/scripts/method-2"
scp "$SCRIPT_DIR/deploy-vps1.sh" root@$VPS1_IP:/tmp/
scp "$SCRIPT_DIR/routing-setup.sh" root@$VPS1_IP:/etc/sdwan/scripts/method-2/ 2>/dev/null || true

# Upload China IPs
if [ -f "$PROJECT_DIR/chinaip.json" ]; then
    log "Uploading China IPs list..."
    scp "$PROJECT_DIR/chinaip.json" root@$VPS1_IP:/etc/sdwan/chinaip.txt
fi

# Upload scripts to VPS2
step "3/6 - Uploading scripts to VPS2..."
scp "$SCRIPT_DIR/deploy-vps2.sh" root@$VPS2_IP:/tmp/

# Deploy VPS1
step "4/6 - Deploying VPS1..."
ssh root@$VPS1_IP "chmod +x /tmp/deploy-vps1.sh && /tmp/deploy-vps1.sh --force" || error "VPS1 deployment failed"
VPS1_WG1_PUBKEY=$(ssh root@$VPS1_IP "cat /etc/wireguard/wg1_publickey")
log "VPS1 deployed. wg1 pubkey: $VPS1_WG1_PUBKEY"

# Deploy VPS2
step "5/6 - Deploying VPS2..."
ssh root@$VPS2_IP "chmod +x /tmp/deploy-vps2.sh && /tmp/deploy-vps2.sh --force '$VPS1_WG1_PUBKEY'" || error "VPS2 deployment failed"
VPS2_WG1_PUBKEY=$(ssh root@$VPS2_IP "cat /etc/wireguard/wg1_publickey")
log "VPS2 deployed. wg1 pubkey: $VPS2_WG1_PUBKEY"

# Update VPS1 with VPS2 pubkey
log "Linking VPS1 ↔ VPS2..."
ssh root@$VPS1_IP "wg set wg1 peer $VPS2_WG1_PUBKEY allowed-ips 10.20.0.2/32,0.0.0.0/0"
ssh root@$VPS1_IP "echo '$VPS2_WG1_PUBKEY' > /etc/wireguard/vps2_wg1_pubkey"

# Verify VPS1 ↔ VPS2 tunnel
log "Verifying VPS1 ↔ VPS2 tunnel..."
sleep 2
ssh root@$VPS1_IP "ping -c 1 -W 2 10.20.0.2" || warn "Cannot ping VPS2 from VPS1"
ssh root@$VPS2_IP "ping -c 1 -W 2 10.20.0.1" || warn "Cannot ping VPS1 from VPS2"

# Generate PC1 config
step "6/6 - Generating PC1 config..."
VPS1_WG0_PUBKEY=$(ssh root@$VPS1_IP "cat /etc/wireguard/wg0_publickey")
PC1_CONFIG="$PROJECT_DIR/configs/method-2/pc1/wg0.conf"

# Generate new PC1 keys
PC1_PRIVKEY=$(wg genkey)
PC1_PUBKEY=$(echo "$PC1_PRIVKEY" | wg pubkey)

mkdir -p "$(dirname "$PC1_CONFIG")"
cat > "$PC1_CONFIG" << EOF
# PC1 - WireGuard Client
# Generated by deploy-all.sh on $(date)

[Interface]
Address = 10.10.0.2/24
PrivateKey = $PC1_PRIVKEY
DNS = 8.8.8.8, 223.5.5.5

[Peer]
PublicKey = $VPS1_WG0_PUBKEY
Endpoint = $VPS1_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF

# Register PC1 with VPS1
ssh root@$VPS1_IP "wg set wg0 peer $PC1_PUBKEY allowed-ips 10.10.0.2/32"
log "PC1 config generated and registered"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    DEPLOYMENT COMPLETE                       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Architecture:"
echo "  PC1 (10.10.0.2) → VPS1 (10.10.0.1/10.20.0.1) → VPS2 (10.20.0.2) → Internet"
echo "                                                  ↑"
echo "                                            NAT Exit Node"
echo ""
echo "Split Routing:"
echo "  • China IPs   → Exit at VPS1 ($VPS1_IP)"
echo "  • Other IPs   → Exit at VPS2 ($VPS2_IP)"
echo ""
echo "PC1 Config: $PC1_CONFIG"
echo ""
echo "To connect PC1:"
echo "  sudo cp $PC1_CONFIG /etc/wireguard/wg0.conf"
echo "  sudo wg-quick up wg0"
echo ""
echo "Test commands:"
echo "  ping 10.10.0.1      # VPS1"
echo "  ping 10.20.0.2      # VPS2"
echo "  traceroute 8.8.8.8  # Should go through VPS2"
echo "  traceroute 223.5.5.5 # Should go through VPS1"
