#!/bin/bash
# Deploy VPS1: WireGuard Server for PC1 (wg0) and VPS2 (wg1)
# Usage: ./deploy-vps1.sh [VPS2_WG1_PUBKEY]

set -e

VPS1_IP="103.109.187.182"
VPS1_GATEWAY="103.109.187.1"
VPS2_IP="103.109.187.179"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[VPS1]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check if running on VPS1
if [[ "$(hostname -I | awk '{print $1}')" != "$VPS1_IP" ]] && [[ "$1" != "--force" ]]; then
    error "This script should run on VPS1 ($VPS1_IP). Use --force to override."
fi

log "=== Deploying VPS1 WireGuard ==="

# Install dependencies
log "Installing dependencies..."
apt-get update -qq
apt-get install -y wireguard ipset iptables -qq

# Generate keys if not exist
log "Checking/generating keys..."
mkdir -p /etc/wireguard

if [ ! -f /etc/wireguard/wg0_privatekey ]; then
    wg genkey | tee /etc/wireguard/wg0_privatekey | wg pubkey > /etc/wireguard/wg0_publickey
    chmod 600 /etc/wireguard/wg0_privatekey
    log "Generated wg0 keys"
fi

if [ ! -f /etc/wireguard/wg1_privatekey ]; then
    wg genkey | tee /etc/wireguard/wg1_privatekey | wg pubkey > /etc/wireguard/wg1_publickey
    chmod 600 /etc/wireguard/wg1_privatekey
    log "Generated wg1 keys"
fi

WG0_PRIVKEY=$(cat /etc/wireguard/wg0_privatekey)
WG0_PUBKEY=$(cat /etc/wireguard/wg0_publickey)
WG1_PRIVKEY=$(cat /etc/wireguard/wg1_privatekey)
WG1_PUBKEY=$(cat /etc/wireguard/wg1_publickey)

log "wg0 pubkey: $WG0_PUBKEY"
log "wg1 pubkey: $WG1_PUBKEY"

# Get VPS2 pubkey
if [ -n "$1" ] && [ "$1" != "--force" ]; then
    VPS2_WG1_PUBKEY="$1"
elif [ -f /etc/wireguard/vps2_wg1_pubkey ]; then
    VPS2_WG1_PUBKEY=$(cat /etc/wireguard/vps2_wg1_pubkey)
else
    warn "VPS2 pubkey not provided. Run deploy-vps2.sh first, then re-run with pubkey."
    VPS2_WG1_PUBKEY="PLACEHOLDER_RUN_DEPLOY_VPS2_FIRST"
fi

# Create wg0.conf (for PC1)
log "Creating wg0.conf..."
cat > /etc/wireguard/wg0.conf << EOF
# VPS1 - WireGuard Server for PC1
# Generated by deploy-vps1.sh

[Interface]
Address = 10.10.0.1/24
ListenPort = 51820
PrivateKey = $WG0_PRIVKEY

PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = /etc/sdwan/scripts/method-2/routing-setup.sh up
PostDown = /etc/sdwan/scripts/method-2/routing-setup.sh down

# PC1 peer will be added dynamically by generate-pc1-config.sh
# Use: wg set wg0 peer <PC1_PUBKEY> allowed-ips 10.10.0.2/32
EOF

# Create wg1.conf (for VPS2)
log "Creating wg1.conf..."
cat > /etc/wireguard/wg1.conf << EOF
# VPS1 - WireGuard Server for VPS2 (exit node)
# Generated by deploy-vps1.sh

[Interface]
Address = 10.20.0.1/24
ListenPort = 51821
PrivateKey = $WG1_PRIVKEY

PostUp = sysctl -w net.ipv4.ip_forward=1

[Peer]
# VPS2 - Exit node
PublicKey = $VPS2_WG1_PUBKEY
AllowedIPs = 10.20.0.2/32
EOF

# Copy routing script (should be uploaded to /tmp first)
log "Setting up routing script..."
mkdir -p /etc/sdwan/scripts/method-2
if [ -f /tmp/routing-setup.sh ]; then
    cp /tmp/routing-setup.sh /etc/sdwan/scripts/method-2/
    chmod +x /etc/sdwan/scripts/method-2/routing-setup.sh
    log "Copied routing-setup.sh"
else
    warn "routing-setup.sh not found in /tmp - upload it first!"
fi

# Copy China IPs if provided
if [ -f /tmp/chinaip.txt ]; then
    cp /tmp/chinaip.txt /etc/sdwan/chinaip.txt
    log "Copied China IPs list"
fi

# Open firewall ports
log "Opening firewall ports..."
ufw allow 51820/udp comment 'WG-PC1' 2>/dev/null || true
ufw allow 51821/udp comment 'WG-VPS2' 2>/dev/null || true

# Start WireGuard
log "Starting WireGuard..."
wg-quick down wg0 2>/dev/null || true
wg-quick down wg1 2>/dev/null || true
wg-quick up wg1
wg-quick up wg0

# Enable on boot
systemctl enable wg-quick@wg0 2>/dev/null || true
systemctl enable wg-quick@wg1 2>/dev/null || true

log "=== VPS1 Deployment Complete ==="
echo ""
echo "wg0 pubkey (for PC1): $WG0_PUBKEY"
echo "wg1 pubkey (for VPS2): $WG1_PUBKEY"
echo ""
echo "Next steps:"
echo "  1. Run deploy-vps2.sh on VPS2"
echo "  2. Run: wg set wg1 peer <VPS2_PUBKEY> allowed-ips 10.20.0.2/32,0.0.0.0/0"
echo "  3. Run generate-pc1-config.sh to create PC1 config"
