#!/bin/bash
# Deploy do2 (VPS1): WireGuard Hub/Router
# Runs ON do2 (152.42.238.137)
# Usage: ./deploy-do2.sh [--force] [FOMINET_WG1_PUBKEY]

set -e

DO2_IP="152.42.238.137"
FOMINET_DDNS="thatnghiep.ddns.net"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[do2]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check if running on do2
if [[ "$(hostname -I | awk '{print $1}')" != "$DO2_IP" ]] && [[ "$1" != "--force" ]]; then
    error "This script should run on do2 ($DO2_IP). Use --force to override."
fi

log "=== Deploying do2 (VPS1) WireGuard ==="

# Install dependencies
log "Installing dependencies..."
apt-get update -qq
apt-get install -y wireguard ipset iptables -qq

# Generate keys if not exist
log "Checking/generating keys..."
mkdir -p /etc/wireguard

if [ ! -f /etc/wireguard/wg0_privatekey ]; then
    wg genkey | tee /etc/wireguard/wg0_privatekey | wg pubkey > /etc/wireguard/wg0_publickey
    chmod 600 /etc/wireguard/wg0_privatekey
    log "Generated wg0 keys"
fi

if [ ! -f /etc/wireguard/wg1_privatekey ]; then
    wg genkey | tee /etc/wireguard/wg1_privatekey | wg pubkey > /etc/wireguard/wg1_publickey
    chmod 600 /etc/wireguard/wg1_privatekey
    log "Generated wg1 keys"
fi

WG0_PRIVKEY=$(cat /etc/wireguard/wg0_privatekey)
WG0_PUBKEY=$(cat /etc/wireguard/wg0_publickey)
WG1_PRIVKEY=$(cat /etc/wireguard/wg1_privatekey)
WG1_PUBKEY=$(cat /etc/wireguard/wg1_publickey)

log "wg0 pubkey: $WG0_PUBKEY"
log "wg1 pubkey: $WG1_PUBKEY"

# Get fominet pubkey
FOMINET_PUBKEY_ARG=""
if [ "$1" = "--force" ] && [ -n "$2" ]; then
    FOMINET_PUBKEY_ARG="$2"
elif [ -n "$1" ] && [ "$1" != "--force" ]; then
    FOMINET_PUBKEY_ARG="$1"
fi

if [ -n "$FOMINET_PUBKEY_ARG" ]; then
    FOMINET_WG1_PUBKEY="$FOMINET_PUBKEY_ARG"
elif [ -f /etc/wireguard/fominet_wg1_pubkey ]; then
    FOMINET_WG1_PUBKEY=$(cat /etc/wireguard/fominet_wg1_pubkey)
else
    warn "fominet pubkey not provided. Setup fominet first, then re-run with pubkey."
    FOMINET_WG1_PUBKEY="PLACEHOLDER_SETUP_FOMINET_FIRST"
fi

# Create wg0.conf (for PC1)
log "Creating wg0.conf..."
cat > /etc/wireguard/wg0.conf << EOF
# do2 (VPS1) - WireGuard Server for PC1
# Generated by deploy-do2.sh

[Interface]
Address = 10.10.0.1/24
ListenPort = 51820
PrivateKey = $WG0_PRIVKEY

PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = /etc/sdwan/routing-setup.sh up
PostDown = /etc/sdwan/routing-setup.sh down

# PC1 peer will be added dynamically by generate-pc1-config.sh
# Use: wg set wg0 peer <PC1_PUBKEY> allowed-ips 10.10.0.2/32
EOF

# Create wg1.conf (for fominet)
log "Creating wg1.conf..."
cat > /etc/wireguard/wg1.conf << EOF
# do2 (VPS1) - WireGuard Tunnel to fominet (Exit Node)
# Generated by deploy-do2.sh

[Interface]
Address = 10.20.0.1/24
ListenPort = 51821
PrivateKey = $WG1_PRIVKEY
Table = off

PostUp = sysctl -w net.ipv4.ip_forward=1

[Peer]
# fominet (OpenWRT exit node)
PublicKey = $FOMINET_WG1_PUBKEY
Endpoint = $FOMINET_DDNS:51821
AllowedIPs = 10.20.0.2/32, 0.0.0.0/0
PersistentKeepalive = 25
EOF

# Copy routing script
log "Setting up routing script..."
mkdir -p /etc/sdwan
if [ -f /tmp/routing-setup.sh ]; then
    cp /tmp/routing-setup.sh /etc/sdwan/routing-setup.sh
    chmod +x /etc/sdwan/routing-setup.sh
    log "Copied routing-setup.sh"
elif [ -f /etc/sdwan/routing-setup.sh ]; then
    log "routing-setup.sh already exists"
else
    warn "routing-setup.sh not found - upload it first!"
fi

# Copy China IPs if provided
if [ -f /tmp/chinaip.txt ]; then
    cp /tmp/chinaip.txt /etc/sdwan/chinaip.txt
    log "Copied China IPs list"
fi

# Open firewall ports
log "Opening firewall ports..."
ufw allow 51820/udp comment 'WG-PC1' 2>/dev/null || true
ufw allow 51821/udp comment 'WG-fominet' 2>/dev/null || true

# Start WireGuard
log "Starting WireGuard..."
wg-quick down wg0 2>/dev/null || true
wg-quick down wg1 2>/dev/null || true

if echo "$FOMINET_WG1_PUBKEY" | grep -q "PLACEHOLDER"; then
    warn "Skipping wg1 start - fominet pubkey is placeholder. Start manually after exchanging keys: wg-quick up wg1"
else
    wg-quick up wg1
fi
wg-quick up wg0

# Enable on boot
systemctl enable wg-quick@wg0 2>/dev/null || true
systemctl enable wg-quick@wg1 2>/dev/null || true

log "=== do2 Deployment Complete ==="
echo ""
echo "wg0 pubkey (for PC1):     $WG0_PUBKEY"
echo "wg1 pubkey (for fominet): $WG1_PUBKEY"
echo ""
echo "Next steps:"
echo "  1. Setup fominet: run setup-uci.sh on fominet"
echo "  2. Exchange pubkeys: wg set wg1 peer <FOMINET_PUBKEY> allowed-ips 10.20.0.2/32,0.0.0.0/0"
echo "  3. Generate PC1 config: ./generate-pc1-config.sh"
