#!/bin/bash
# Deploy VPS2: WireGuard Client connecting to VPS1 (exit node)
# Usage: ./deploy-vps2.sh [VPS1_WG1_PUBKEY]

set -e

VPS1_IP="103.109.187.182"
VPS2_IP="103.109.187.179"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[VPS2]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check if running on VPS2
if [[ "$(hostname -I | awk '{print $1}')" != "$VPS2_IP" ]] && [[ "$1" != "--force" ]]; then
    error "This script should run on VPS2 ($VPS2_IP). Use --force to override."
fi

log "=== Deploying VPS2 WireGuard (Exit Node) ==="

# Install dependencies
log "Installing dependencies..."
apt-get update -qq
apt-get install -y wireguard -qq

# Generate keys if not exist
log "Checking/generating keys..."
mkdir -p /etc/wireguard

if [ ! -f /etc/wireguard/wg1_privatekey ]; then
    wg genkey | tee /etc/wireguard/wg1_privatekey | wg pubkey > /etc/wireguard/wg1_publickey
    chmod 600 /etc/wireguard/wg1_privatekey
    log "Generated wg1 keys"
fi

WG1_PRIVKEY=$(cat /etc/wireguard/wg1_privatekey)
WG1_PUBKEY=$(cat /etc/wireguard/wg1_publickey)

log "wg1 pubkey: $WG1_PUBKEY"

# Get VPS1 pubkey
if [ -n "$1" ] && [ "$1" != "--force" ]; then
    VPS1_WG1_PUBKEY="$1"
elif [ -f /etc/wireguard/vps1_wg1_pubkey ]; then
    VPS1_WG1_PUBKEY=$(cat /etc/wireguard/vps1_wg1_pubkey)
else
    warn "VPS1 pubkey not provided. Run deploy-vps1.sh first to get the pubkey."
    VPS1_WG1_PUBKEY="PLACEHOLDER_RUN_DEPLOY_VPS1_FIRST"
fi

# Detect network interface
ETH_IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
[ -z "$ETH_IFACE" ] && ETH_IFACE="eth0"
log "Using network interface: $ETH_IFACE"

# Create wg1.conf
log "Creating wg1.conf..."
cat > /etc/wireguard/wg1.conf << EOF
# VPS2 - WireGuard Client connecting to VPS1 (Exit Node)
# Generated by deploy-vps2.sh

[Interface]
Address = 10.20.0.2/24
PrivateKey = $WG1_PRIVKEY

# Enable IP forwarding and NAT
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -t nat -A POSTROUTING -s 10.20.0.0/24 -o $ETH_IFACE -j MASQUERADE
PostUp = iptables -t nat -A POSTROUTING -s 10.10.0.0/24 -o $ETH_IFACE -j MASQUERADE
PostUp = iptables -A FORWARD -i wg1 -o $ETH_IFACE -j ACCEPT
PostUp = iptables -A FORWARD -i $ETH_IFACE -o wg1 -m state --state RELATED,ESTABLISHED -j ACCEPT

PostDown = iptables -t nat -D POSTROUTING -s 10.20.0.0/24 -o $ETH_IFACE -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.10.0.0/24 -o $ETH_IFACE -j MASQUERADE
PostDown = iptables -D FORWARD -i wg1 -o $ETH_IFACE -j ACCEPT
PostDown = iptables -D FORWARD -i $ETH_IFACE -o wg1 -m state --state RELATED,ESTABLISHED -j ACCEPT

[Peer]
# VPS1 - Hub/Router
PublicKey = $VPS1_WG1_PUBKEY
Endpoint = $VPS1_IP:51821
AllowedIPs = 10.20.0.0/24, 10.10.0.0/24
PersistentKeepalive = 25
EOF

# Start WireGuard
log "Starting WireGuard..."
wg-quick down wg1 2>/dev/null || true
wg-quick up wg1

# Enable on boot
systemctl enable wg-quick@wg1 2>/dev/null || true

log "=== VPS2 Deployment Complete ==="
echo ""
echo "wg1 pubkey: $WG1_PUBKEY"
echo ""
echo "Next steps:"
echo "  1. Copy this pubkey to VPS1:"
echo "     ssh root@$VPS1_IP \"wg set wg1 peer $WG1_PUBKEY allowed-ips 10.20.0.2/32,0.0.0.0/0\""
echo "  2. Or save it: echo '$WG1_PUBKEY' > /etc/wireguard/vps2_wg1_pubkey"
echo ""
echo "Verify connection:"
echo "  wg show wg1"
echo "  ping 10.20.0.1"
