#!/bin/bash
# Generate PC1 WireGuard config and register with do2 (VPS1)
# Usage: ./generate-pc1-config.sh [DO2_HOST] [DO2_WG0_PUBKEY] [OUTPUT_FILE]

set -e

DO2_HOST="${1:-do2}"
DO2_WG0_PUBKEY="${2:-}"
OUTPUT_FILE="${3:-/tmp/pc1-wg0.conf}"
DO2_IP="152.42.238.137"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${GREEN}[PC1]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

log "=== Generating PC1 WireGuard Config ==="

# Generate PC1 keys
PC1_PRIVKEY=$(wg genkey)
PC1_PUBKEY=$(echo "$PC1_PRIVKEY" | wg pubkey)

log "Generated PC1 keys"
log "PC1 pubkey: $PC1_PUBKEY"

# Get do2 wg0 pubkey
if [ -z "$DO2_WG0_PUBKEY" ]; then
    log "Fetching do2 wg0 pubkey..."
    DO2_WG0_PUBKEY=$(ssh $DO2_HOST "cat /etc/wireguard/wg0_publickey" 2>/dev/null) || {
        error "Cannot fetch do2 pubkey. Provide it as second argument."
    }
fi

log "do2 wg0 pubkey: $DO2_WG0_PUBKEY"

# Create PC1 config
cat > "$OUTPUT_FILE" << EOF
# PC1 - WireGuard Client connecting to do2 (VPS1)
# Generated by generate-pc1-config.sh on $(date)
# Split routing: China IPs → fominet, Other IPs → do2

[Interface]
Address = 10.10.0.2/24
PrivateKey = $PC1_PRIVKEY
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = $DO2_WG0_PUBKEY
Endpoint = $DO2_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF

log "Config written to: $OUTPUT_FILE"

# Register PC1 with do2
log "Registering PC1 with do2..."
ssh $DO2_HOST "wg set wg0 peer $PC1_PUBKEY allowed-ips 10.10.0.2/32" 2>/dev/null && {
    log "PC1 registered with do2"
} || {
    warn "Could not auto-register. Run on do2:"
    echo "  wg set wg0 peer $PC1_PUBKEY allowed-ips 10.10.0.2/32"
}

log "=== PC1 Config Generation Complete ==="
echo ""
echo "Config file: $OUTPUT_FILE"
echo ""
echo "To use on PC1:"
echo "  Linux:   sudo cp $OUTPUT_FILE /etc/wireguard/wg0.conf && sudo wg-quick up wg0"
echo "  macOS:   Import into WireGuard app"
echo "  Windows: Import into WireGuard app"
echo ""
echo "Test:"
echo "  ping 10.10.0.1     # do2"
echo "  ping 10.20.0.2     # fominet"
echo "  traceroute 8.8.8.8 # Should exit via do2 ($DO2_IP)"
echo "  traceroute 223.5.5.5 # Should exit via fominet"
