#!/bin/bash
# Generate PC1 WireGuard config and register with VPS1
# Usage: ./generate-pc1-config.sh [VPS1_HOST] [OUTPUT_FILE]

set -e

VPS1_IP="${1:-103.109.187.182}"
VPS1_WG0_PUBKEY="${2:-}"
OUTPUT_FILE="${3:-/tmp/pc1-wg0.conf}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[PC1]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

log "=== Generating PC1 WireGuard Config ==="

# Generate PC1 keys
PC1_PRIVKEY=$(wg genkey)
PC1_PUBKEY=$(echo "$PC1_PRIVKEY" | wg pubkey)

log "Generated PC1 keys"
log "PC1 pubkey: $PC1_PUBKEY"

# Get VPS1 wg0 pubkey
if [ -z "$VPS1_WG0_PUBKEY" ]; then
    log "Fetching VPS1 wg0 pubkey..."
    VPS1_WG0_PUBKEY=$(ssh root@$VPS1_IP "cat /etc/wireguard/wg0_publickey" 2>/dev/null) || {
        error "Cannot fetch VPS1 pubkey. Provide it as second argument."
    }
fi

log "VPS1 wg0 pubkey: $VPS1_WG0_PUBKEY"

# Create PC1 config
cat > "$OUTPUT_FILE" << EOF
# PC1 - WireGuard Client connecting to VPS1
# Generated by generate-pc1-config.sh
# Traffic: PC1 → VPS1 → VPS2 (exit) / China IPs exit at VPS1

[Interface]
Address = 10.10.0.2/24
PrivateKey = $PC1_PRIVKEY
DNS = 8.8.8.8, 223.5.5.5

[Peer]
PublicKey = $VPS1_WG0_PUBKEY
Endpoint = $VPS1_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF

log "Config written to: $OUTPUT_FILE"

# Register PC1 with VPS1
log "Registering PC1 with VPS1..."
ssh root@$VPS1_IP "wg set wg0 peer $PC1_PUBKEY allowed-ips 10.10.0.2/32" 2>/dev/null && {
    log "PC1 registered with VPS1"
} || {
    warn "Could not auto-register. Run on VPS1:"
    echo "  wg set wg0 peer $PC1_PUBKEY allowed-ips 10.10.0.2/32"
}

log "=== PC1 Config Generation Complete ==="
echo ""
echo "Config file: $OUTPUT_FILE"
echo ""
echo "To use on PC1:"
echo "  Linux:   sudo cp $OUTPUT_FILE /etc/wireguard/wg0.conf && sudo wg-quick up wg0"
echo "  macOS:   Import into WireGuard app"
echo "  Windows: Import into WireGuard app"
echo ""
echo "Test connection:"
echo "  ping 10.10.0.1    # VPS1"
echo "  ping 10.20.0.2    # VPS2"
echo "  curl ifconfig.me  # Should show VPS2 IP for non-China, VPS1 for China"
