#!/bin/bash
#===============================================================================
# VPS2 Setup Script - WireGuard Client + NAT (Method 1 - Single Tunnel)
# Chức năng: WG Client kết nối đến VPS1, NAT traffic ra Internet
# Script tự động tạo wg0.conf với keys đã điền sẵn
#===============================================================================

set -e

# ===== CẤU HÌNH =====
VPS1_PUBLIC_IP=""
VPS1_PUBLIC_KEY=""

# Load config.env nếu có
if [ -f "/root/sd-wan/config.env" ]; then
    source /root/sd-wan/config.env
    VPS1_PUBLIC_IP="$VPS1_HOST"
fi

# Nhận VPS1_PUBLIC_KEY từ argument nếu có
if [ -n "$1" ]; then
    VPS1_PUBLIC_KEY="$1"
fi

echo "================================================"
echo "  VPS2 WireGuard Client Setup (Method 1)"
echo "================================================"

# Kiểm tra root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Vui lòng chạy script với quyền root (sudo)"
    exit 1
fi

# Kiểm tra VPS1 IP
if [ -z "$VPS1_PUBLIC_IP" ]; then
    echo "❌ Thiếu VPS1_PUBLIC_IP! Cung cấp qua config.env hoặc biến môi trường"
    exit 1
fi

echo "    📍 VPS1 IP: $VPS1_PUBLIC_IP"
if [ -n "$VPS1_PUBLIC_KEY" ]; then
    echo "    🔑 VPS1 Public Key: ${VPS1_PUBLIC_KEY:0:20}..."
fi

echo ""
echo "[1/4] Cài đặt WireGuard..."
apt update
apt install -y wireguard wireguard-tools iptables

echo ""
echo "[2/4] Tạo key pair..."
cd /etc/wireguard

if [ ! -f "vps2_privatekey" ]; then
    wg genkey | tee vps2_privatekey | wg pubkey > vps2_publickey
    chmod 600 vps2_privatekey
    echo "    ✅ Keys đã được tạo"
else
    echo "    ⚠️  Keys đã tồn tại, sử dụng keys hiện có..."
fi

VPS2_PRIVATE_KEY=$(cat /etc/wireguard/vps2_privatekey)
VPS2_PUBLIC_KEY=$(cat /etc/wireguard/vps2_publickey)

echo ""
echo "[3/4] Tạo file wg0.conf..."

# Xác định main interface
MAIN_INTERFACE=$(ip route | grep default | awk '{print $5}' | head -1)

# Nếu có VPS1_PUBLIC_KEY thì dùng, không thì để placeholder
if [ -z "$VPS1_PUBLIC_KEY" ]; then
    VPS1_PUBLIC_KEY="<VPS1_PUBLIC_KEY>"
fi

# Tạo wg0.conf
cat > /etc/wireguard/wg0.conf << EOF
#===============================================================================
# VPS2 WireGuard Client Configuration (Method 1 - Single Tunnel)
# Auto-generated by setup.sh
#===============================================================================

[Interface]
Address = 10.0.0.3/24
PrivateKey = ${VPS2_PRIVATE_KEY}

# NAT Rules - Forward traffic ra Internet
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o ${MAIN_INTERFACE} -j MASQUERADE
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -j ACCEPT

PostDown = iptables -t nat -D POSTROUTING -s 10.0.0.0/24 -o ${MAIN_INTERFACE} -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT

#===============================================================================
# PEER: VPS1 Server
#===============================================================================
[Peer]
PublicKey = ${VPS1_PUBLIC_KEY}
Endpoint = ${VPS1_PUBLIC_IP}:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
EOF

chmod 600 /etc/wireguard/wg0.conf
echo "    ✅ wg0.conf đã được tạo"

echo ""
echo "[4/4] Hoàn tất (WireGuard chưa được bật)..."

echo ""
echo "================================================"
echo "  ✅ VPS2 Setup hoàn tất!"
echo "================================================"
echo ""
echo "🔑 VPS2 PUBLIC KEY:"
echo "================================================"
echo "$VPS2_PUBLIC_KEY"
echo "================================================"
echo ""
echo "📝 Các bước tiếp theo:"
echo "  1. Copy VPS2 public key ở trên"
echo "  2. Thay <VPS2_PUBLIC_KEY> trong /etc/wireguard/wg0.conf của VPS1"
if [ "$VPS1_PUBLIC_KEY" == "<VPS1_PUBLIC_KEY>" ]; then
    echo "  3. Thay <VPS1_PUBLIC_KEY> trong /etc/wireguard/wg0.conf (file này)"
fi
echo "  4. Bật WireGuard trên cả 2 VPS: wg-quick up wg0"
echo ""
