# =============================================================================
# PC0 (vina7) - wg0: Client kết nối tới do2 (VPS1)
# Host: vina7 (103.109.187.182)
# Subnet: 10.10.0.0/24 (PC0 <-> VPS1)
# =============================================================================

[Interface]
Address = 10.10.0.3/24
PrivateKey = sLbxs2YtpxiL0Lt2VgAg78ZlnbUoNi6uPUJ5LAfKT1g=
DNS = 8.8.8.8, 1.1.1.1

[Peer]
# do2 (VPS1)
PublicKey = NqBPKP5g2qYt41dBFDH/Q30HzvrXC+6GuE+CNRUYGHE=
Endpoint = 152.42.238.137:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
