#!/bin/bash
#===============================================================================
# VPS1 Setup Script - WireGuard Server (Method 1 - Single Tunnel)
# Chức năng: WG Server nhận kết nối từ PC và VPS2, forward traffic giữa chúng
# Script tự động tạo wg0.conf với keys đã điền sẵn
#===============================================================================

set -e

echo "================================================"
echo "  VPS1 WireGuard Server Setup (Method 1)"
echo "================================================"

# Kiểm tra root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Vui lòng chạy script với quyền root (sudo)"
    exit 1
fi

echo ""
echo "[1/4] Cài đặt WireGuard..."
apt update
apt install -y wireguard wireguard-tools iptables

echo ""
echo "[2/4] Tạo key pair..."
cd /etc/wireguard

if [ ! -f "vps1_privatekey" ]; then
    wg genkey | tee vps1_privatekey | wg pubkey > vps1_publickey
    chmod 600 vps1_privatekey
    echo "    ✅ Keys đã được tạo"
else
    echo "    ⚠️  Keys đã tồn tại, sử dụng keys hiện có..."
fi

VPS1_PRIVATE_KEY=$(cat /etc/wireguard/vps1_privatekey)
VPS1_PUBLIC_KEY=$(cat /etc/wireguard/vps1_publickey)

echo ""
echo "[3/4] Tạo file wg0.conf..."

# Tạo wg0.conf với private key đã điền sẵn
cat > /etc/wireguard/wg0.conf << EOF
#===============================================================================
# VPS1 WireGuard Server Configuration (Method 1 - Single Tunnel)
# Auto-generated by setup.sh
#===============================================================================

[Interface]
Address = 10.0.0.1/24
PrivateKey = ${VPS1_PRIVATE_KEY}
ListenPort = 51820

# IP Forward Rules
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -A FORWARD -i wg0 -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -o wg0 -j ACCEPT

#===============================================================================
# PEER: PC Client
#===============================================================================
[Peer]
# TODO: Thay bằng public key của PC
PublicKey = <PC_PUBLIC_KEY>
AllowedIPs = 10.0.0.2/32

#===============================================================================
# PEER: VPS2 Client (Gateway ra Internet)
#===============================================================================
[Peer]
# TODO: Thay bằng public key của VPS2
PublicKey = <VPS2_PUBLIC_KEY>
AllowedIPs = 10.0.0.3/32, 0.0.0.0/0
EOF

chmod 600 /etc/wireguard/wg0.conf
echo "    ✅ wg0.conf đã được tạo"

echo ""
echo "[4/4] Hoàn tất (WireGuard chưa được bật)..."

echo ""
echo "================================================"
echo "  ✅ VPS1 Setup hoàn tất!"
echo "================================================"
echo ""
echo "🔑 VPS1 PUBLIC KEY:"
echo "================================================"
echo "$VPS1_PUBLIC_KEY"
echo "================================================"
echo ""
echo "📝 Các bước tiếp theo:"
echo "  1. Chờ VPS2 setup xong để lấy VPS2 public key"
echo "  2. Thay <VPS2_PUBLIC_KEY> trong /etc/wireguard/wg0.conf"
echo "  3. Thay <PC_PUBLIC_KEY> trong /etc/wireguard/wg0.conf"
echo "  4. Bật WireGuard: wg-quick up wg0"
echo ""
