# =============================================================================
# do2 (VPS1) - wg0: Nhận traffic từ PC1
# Host: do2 (152.42.238.137)
# Subnet: 10.10.0.0/24 (PC1 <-> VPS1)
# =============================================================================

[Interface]
Address = 10.10.0.1/24
ListenPort = 51820
PrivateKey = aJ3uojwSAVrivX23HVU/SwmzQoQr60itPnOf5HRRgns=

# Routing setup: ipset + fwmark + policy routing
PostUp = /etc/sdwan/routing-setup.sh up
PostDown = /etc/sdwan/routing-setup.sh down

[Peer]
# PC1
PublicKey = CsB1dL3jxp8Xas06ro9HxUHUsrsGLB7ikN8HsRpA0Vk=
AllowedIPs = 10.10.0.2/32

[Peer]
# PC0 (vina7)
PublicKey = 7OE6S77nYS08BdltFumjp5ATlDDtQ+xAUB7GF74AsxM=
AllowedIPs = 10.10.0.3/32
