# =============================================================================
# PC1 - wg0: Client kết nối tới do2 (VPS1)
# Host: PC1 (local machine)
# Subnet: 10.10.0.0/24 (PC1 <-> VPS1)
# =============================================================================

[Interface]
Address = 10.10.0.2/24
PrivateKey = iEmqLneYcm7riWLPBkZrcGwBcMkaHLmL/zKovr5T7XA=
DNS = 8.8.8.8, 1.1.1.1

[Peer]
# do2 (VPS1)
PublicKey = NqBPKP5g2qYt41dBFDH/Q30HzvrXC+6GuE+CNRUYGHE=
Endpoint = 152.42.238.137:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
